import { api } from '@/services/api'
import { toPaginated, type ApiPage } from '@/services/adapters/paginate'
import type { ApiResponse } from '@/types/api'
import type { PaginatedResponse } from '@/types/employee'
import type { HelpdeskTicket, NewTicketPayload, TicketActivity, TicketAttachment, TicketCategory, TicketPriority, TicketQuery, TicketStatus, TicketType } from '@/types/helpdesk'

/**
 * Helpdesk tickets, Laravel adapter.
 *   GET /api/helpdesk/tickets, GET /api/helpdesk/tickets/{id}, POST /api/helpdesk/tickets
 *   POST /api/helpdesk/tickets/{id}/replies | /attachments | /cancel
 * The ticket number (INC-2026-00001) is generated by Laravel. Only the knowledge base stays on sample data: it has no table yet.
 */

interface ApiTicket {
  id: number
  ticket_number: string
  category: TicketCategory
  type: TicketType
  subject: string
  description: string
  location: string | null
  device: string | null
  operating_system: string | null
  asset_tag: string | null
  priority: TicketPriority
  status: TicketStatus
  status_label?: string | null
  handled_by?: string | null
  created_at: string
  updated_at: string
  replies?: { id: number; author: string; message: string; created_at: string }[]
  attachments?: { id: number; filename: string; mime_type: string; file_size: number }[]
  is_sample?: boolean
}

const extension = (name: string) => (name.split('.').pop() ?? 'file').toUpperCase()
const toAttachment = (a: { id: number; filename: string; file_size: number }): TicketAttachment => ({ id: String(a.id), name: a.filename, fileType: extension(a.filename), size: a.file_size })

function toTicket(t: ApiTicket): HelpdeskTicket {
  const activity: TicketActivity[] = [{ id: 'created', kind: 'event', actor: 'system', actorLabel: 'System', message: 'Ticket submitted', createdAt: t.created_at }]
  for (const reply of t.replies ?? []) {
    const mine = reply.author === 'You'
    activity.push({ id: `reply-${reply.id}`, kind: 'reply', actor: mine ? 'employee' : 'support', actorLabel: mine ? 'You' : reply.author === 'IT support' ? 'IT Support' : reply.author, message: reply.message, createdAt: reply.created_at })
  }
  return {
    id: String(t.id),
    reference: t.ticket_number,
    subject: t.subject,
    description: t.description,
    type: t.type,
    category: t.category,
    status: t.status,
    statusLabel: t.status_label ?? undefined,
    handledBy: t.handled_by ?? undefined,
    priority: t.priority,
    createdAt: t.created_at,
    updatedAt: t.updated_at,
    location: t.location ?? undefined,
    deviceType: t.device ?? undefined,
    operatingSystem: t.operating_system ?? undefined,
    assetTag: t.asset_tag ?? undefined,
    requesterId: '',
    attachments: (t.attachments ?? []).map(toAttachment),
    activity,
    isSample: t.is_sample,
  }
}

const SORTS = { updated: ['updated_at', 'desc'], newest: ['created_at', 'desc'], oldest: ['created_at', 'asc'] } as const

export async function getTickets(query: TicketQuery = {}): Promise<PaginatedResponse<HelpdeskTicket>> {
  const [sort, direction] = SORTS[query.sort ?? 'updated']
  const page = await api.get<ApiPage<ApiTicket>>('/api/helpdesk/tickets', {
    search: query.search?.trim(), status: query.status, category: query.category, priority: query.priority,
    sort, direction, page: query.page, per_page: query.perPage,
  })
  return toPaginated(page, toTicket)
}

export async function getRecentTickets(limit = 3): Promise<HelpdeskTicket[]> {
  const page = await api.get<ApiPage<ApiTicket>>('/api/helpdesk/tickets', { sort: 'updated_at', direction: 'desc', per_page: limit })
  return page.data.map(toTicket)
}

export async function getTicket(id: string): Promise<HelpdeskTicket | null> {
  let numeric = id
  if (!/^\d+$/.test(id)) {
    const found = await api.get<ApiPage<ApiTicket>>('/api/helpdesk/tickets', { search: id, per_page: 5 })
    const match = found.data.find((t) => t.ticket_number.toLowerCase() === id.toLowerCase())
    if (!match) return null
    numeric = String(match.id)
  }
  try {
    return toTicket((await api.get<ApiResponse<ApiTicket>>(`/api/helpdesk/tickets/${numeric}`)).data)
  } catch (error) {
    if ((error as { status?: number }).status === 404) return null
    throw error
  }
}

async function upload(ticketId: number | string, file: File): Promise<boolean> {
  const form = new FormData()
  form.append('file', file)
  try {
    await api.upload(`/api/helpdesk/tickets/${ticketId}/attachments`, form)
    return true
  } catch {
    return false
  }
}

export async function createTicket(payload: NewTicketPayload): Promise<HelpdeskTicket> {
  const created = await api.post<ApiResponse<ApiTicket>>('/api/helpdesk/tickets', {
    type: payload.type,
    category: payload.category,
    subject: payload.subject.trim(),
    description: payload.description.trim(),
    location: payload.location?.trim() || undefined,
    device: payload.deviceType?.trim() || undefined,
    operating_system: payload.operatingSystem?.trim() || undefined,
    asset_tag: payload.assetTag?.trim() || undefined,
  })
  if (payload.file) await upload(created.data.id, payload.file)
  return (await getTicket(String(created.data.id))) ?? toTicket(created.data)
}

export async function replyToTicket(id: string, reply: { message: string; file?: File }): Promise<HelpdeskTicket> {
  await api.post(`/api/helpdesk/tickets/${id}/replies`, { message: reply.message.trim() })
  if (reply.file) await upload(id, reply.file)
  const updated = await getTicket(id)
  if (!updated) throw new Error('Ticket not found')
  return updated
}

export async function cancelTicket(id: string): Promise<HelpdeskTicket> {
  return toTicket((await api.post<ApiResponse<ApiTicket>>(`/api/helpdesk/tickets/${id}/cancel`)).data)
}
